// import amqp from 'amqplib/callback_api.js';
const amqp = require('amqplib/callback_api.js')
const config = require('config')

const data_0 = {
    "info": {
        "name": "test-1",
        "reservationNumber": 1110111011,
        "centerCode": 111,
        "examDate": "1989-02-17",
        "reportDate": "1989-02-19",
    },
    "KOSS": {
        "autonomy": {"distribution": "하위 25", "score": 13},
        "compensation": {"distribution": "상위 50", "score": 18},
        "culture": {"distribution": "상위 25", "score": 33},
        "jobInstability": {"distribution": "하위 25", "score": 46},
        "relationship": {"distribution": "상위 25", "score": 80},
        "requirements": {"distribution": "하위 50", "score": 100},
        "system": {"distribution": "상위 50", "score": 35},
        "total": {
            "distribution" : "상위 25",
            "score" : 55,
            "scoreMean" : 12.4,
            "level": 24,
            "result": "약간 심함",
            "byYear": 24,
            "details": "스트레스 측정 점수는 39.5점으로, 참고치 하위 25%에 해당합니다.",
        }
    },
    "PHQ9" : {
        "level": 24,
        "result": "정상",
        "score" : 15,
        "riskRate": 18,
        "description": "우울 관련 증상이 거의 보이지 않음",
        "guidance": "",
        "advice": "",
        "byYear": 15,
        "details": "검사 결과는 경미한 수준의 우울감 위험이 있습니다.",
    },
    "GAD7" : {
        "level": 24,
        "result": "불안아님",
        "score" : 15,
        "riskRate": 18,
        "description": "불안 관련 증상이 거의 보이지 않음",
        "guidance": "",
        "advice": "",
        "byYear": 44,
        "details": "검사 결과는 불안감이 없습니다.",
    },
    "ADNM4" : {
        "level": 24,
        "result": "적응장애아님",
        "score" : 15,
        "riskRate": 18,
        "description": "일상생활 적응에 지장을 초래하지 않음",
        "guidance": "",
        "advice": "",
        "byYear": 22,
        "details": "검사 결과는 적응 스트레스가 없습니다.",
    },
    "PCPTSD5" : {
        "level": 24,
        "result": "PTSD아님",
        "score" : 15,
        "riskRate": 18,
        "description": "일상생활을 저해하는 스트레스가 아님",
        "guidance": "",
        "advice": "",
        "byYear": 22,
        "details": "검사 결과는 외상 스트레스가 없습니다.",
    },
    "ISI" : {
        "level": 24,
        "result": "불면증아님",
        "score" : 15,
        "riskRate": 18,
        "description": "임상적 불면증이 거의 없음",
        "guidance": "",
        "advice": "",
        "byYear": 44,
        "details": "검사 결과는 불면증이 없습니다.",
    },
    "CSS" : {
        "result": "CSS미검사자",
        "description": "정상입니다. 해당 검사를 수행할 필요가 없습니다.",
        "guidance": "",
        "advice": "",
        "details": "우울감 설문 결과에 따라 극단적 선택 가능성 검사를 진행하지 않았습니다.",
    },
}
const data_1 =
    {
        "info": {
            "name": "test-2",
            "reservationNumber": 1120112011,
            "centerCode": 112,
            "examDate": "1989-02-17",
            "reportDate": "1989-02-19",
        },
        "KOSS": {
            "autonomy": {"distribution": "하위 25", "score": 13},
            "compensation": {"distribution": "상위 50", "score": 18},
            "culture": {"distribution": "상위 25", "score": 33},
            "jobInstability": {"distribution": "하위 25", "score": 46},
            "relationship": {"distribution": "상위 25", "score": 80},
            "requirements": {"distribution": "하위 50", "score": 100},
            "system": {"distribution": "상위 50", "score": 35},
            "total": {
                "distribution" : "상위 25",
                "score" : 55,
                "scoreMean" : 12.4,
                "level": 24,
                "result": "약간 심함",
                "byYear": 24,
                "details": "스트레스 측정 점수는 39.5점으로, 참고치 하위 25%에 해당합니다.",
            }
        },
        "PHQ9" : {
            "level": 24,
            "result": "경미함",
            "score" : 25,
            "riskRate": 28,
            "description": "경미한 수준의 우울감이 있음",
            "guidance": "",
            "advice": "",
            "byYear": 22,
            "details": "검사 결과는 경미한 수준의 우울감 위험이 있습니다.",
        },
        "GAD7" : {
            "level": 45,
            "result": "경미함",
            "score" : 33,
            "riskRate": 44,
            "description": "다소 경미한 수준의 걱정과 불안이 있음",
            "guidance": "직업, 사회적 영향이 있는지 주의 필요함",
            "advice": "주의필요",
            "byYear": 33,
            "details": "검사 결과는 경미함 수준의 불안감을 자주 느끼고 있습니다. 불안장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 주의가 필요합니다.",
        },
        "ADNM4" : {
            "level": 24,
            "result": "적응장애아님",
            "score" : 15,
            "riskRate": 18,
            "description": "일상생활 적응에 지장을 초래하지 않음",
            "guidance": "",
            "advice": "",
            "byYear": 22,
            "details": "검사 결과는 적응 스트레스가 없습니다.",
        },
        "PCPTSD5" : {
            "level": 24,
            "result": "PTSD아님",
            "score" : 15,
            "riskRate": 18,
            "description": "일상생활을 저해하는 스트레스가 아님",
            "guidance": "",
            "advice": "",
            "byYear": 22,
            "details": "검사 결과는 외상 스트레스가 없습니다.",
        },
        "ISI" : {
            "level": 45,
            "result": "경미함",
            "score" : 33,
            "riskRate": 35,
            "description": "경미한 불면증이 있는 것으로 보임",
            "guidance": "2주 이상 지속 시 전문가의 도움이 필요함",
            "advice": "주의필요",
            "byYear": 22,
            "details": "검사 결과는 경미한 수준의 불면증을 자주 느끼고 있습니다. 2주 이상 지속 시 전문가의 도움이 필요합니다. 수면 장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "CSS" : {
            "result": "자살위험아님",
            "description": "위험한 수준의 자살 사고가 보이지 않음",
            "guidance": "",
            "advice": "",
            "details": "검사 결과는 자살사고 위험이 없습니다.",
        },
    }
const data_2 =
    {
        "info": {
            "name": "test-3",
            "reservationNumber": 1130113011,
            "centerCode": 113,
            "examDate": "1989-02-17",
            "reportDate": "1989-02-19",
        },
        "KOSS": {
            "autonomy": {"distribution": "하위 25", "score": 13},
            "compensation": {"distribution": "상위 50", "score": 18},
            "culture": {"distribution": "상위 25", "score": 33},
            "jobInstability": {"distribution": "하위 25", "score": 46},
            "relationship": {"distribution": "상위 25", "score": 80},
            "requirements": {"distribution": "하위 50", "score": 100},
            "system": {"distribution": "상위 50", "score": 35},
            "total": {
                "distribution" : "상위 25",
                "score" : 55,
                "scoreMean" : 12.4,
                "level": 24,
                "result": "약간 심함",
                "byYear": 24,
                "details": "스트레스 측정 점수는 39.5점으로, 참고치 하위 25%에 해당합니다.",
            }
        },
        "PHQ9" : {
            "level": 45,
            "result": "중간",
            "score" : 45,
            "riskRate": 48,
            "description": "중간 수준의 우울감을 자주 느낌",
            "guidance": "직업, 사회적 영향이 있는지 주의 필요함",
            "advice": "주의 필요",
            "byYear": 24,
            "details": "검사 결과는 중간 수준의 우울감을 자주 느끼고 있습니다. 우울증 진단은 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 주의가 필요합니다.",
        },
        "GAD7" : {
            "level": 66,
            "result": "중간",
            "score" : 68,
            "riskRate": 54,
            "description": "주의가 필요한 과도한 걱정, 불안을 느낌",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 33,
            "details": "검사 결과는 중간 수준의 불안감을 자주 느끼고 있습니다. 불안장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "ADNM4" : {
            "level": 87,
            "result": "심각함",
            "score" : 69,
            "riskRate": 87,
            "description": "일상생활 적응에 어려움이 있을 수 있음",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 심각한 수준의 적응 스트레스를 자주 느끼고 있습니다. 적응장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "PCPTSD5" : {
            "level": 45,
            "result": "중간",
            "score" : 38,
            "riskRate": 55,
            "description": "외상사건 관련 상황에 불편감을 느낌",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 중간 수준의 외상 스트레스를 자주 느끼고 있습니다. PTSD 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "ISI" : {
            "level": 66,
            "result": "약간심함",
            "score" : 65,
            "riskRate": 66,
            "description": "중한 수준의 불면증이 있는 것으로 보임",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 약간 심한 수준의 불면증을 자주 느끼고 있습니다. 2주 이상 지속 시 전문가의 도움이 필요합니다. 수면 장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "CSS" : {
            "result": "자살행동고려",
            "description": "자살 시도를 할 가능성이 있으며, 자살 사고나 행동을 저지할 수 있는 보호 요인이 없는 것으로 보입니다.",
            "guidance": "추가 평가 및 전문가의 도움 즉시 권고",
            "advice": "전문도움필요",
            "details": "검사 결과는 자살 시도를 할 가능성이 있으며, 자살 사고나 행동을 저지할 수 있는 보호 요인이 없는 것으로 보입니다.",
        },
    }
const data_3 =
    {
        "info": {
            "name": "test-4",
            "reservationNumber": 2110211021,
            "centerCode": 211,
            "examDate": "1989-02-17",
            "reportDate": "1989-02-19",
        },
        "KOSS": {
            "autonomy": {"distribution": "하위 25", "score": 13},
            "compensation": {"distribution": "상위 50", "score": 18},
            "culture": {"distribution": "상위 25", "score": 33},
            "jobInstability": {"distribution": "하위 25", "score": 46},
            "relationship": {"distribution": "상위 25", "score": 80},
            "requirements": {"distribution": "하위 50", "score": 100},
            "system": {"distribution": "상위 50", "score": 35},
            "total": {
                "distribution" : "상위 25",
                "score" : 55,
                "scoreMean" : 12.4,
                "level": 24,
                "result": "약간 심함",
                "byYear": 24,
                "details": "스트레스 측정 점수는 39.5점으로, 참고치 하위 25%에 해당합니다.",
            }
        },
        "PHQ9" : {
            "level": 66,
            "result": "약간심함",
            "score" : 68,
            "riskRate": 70,
            "description": "약간 심한 수준의 우울감을 자주 느낌",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 25,
            "details": "검사 결과는 약간 심한 수준의 우울감을 자주 느끼고 있습니다. 우울증 진단은 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "GAD7" : {
            "level": 87,
            "result": "심각함",
            "score" : 90,
            "riskRate": 87,
            "description": "심각하고 과도한 걱정, 불안을 느낌",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 심각한 수준의 불안감을 자주 느끼고 있습니다. 불안장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "ADNM4" : {
            "level": 87,
            "result": "심각함",
            "score" : 69,
            "riskRate": 87,
            "description": "일상생활 적응에 어려움이 있을 수 있음",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 심각한 수준의 적응 스트레스를 자주 느끼고 있습니다. 적응장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "PCPTSD5" : {
            "level": 45,
            "result": "중간",
            "score" : 38,
            "riskRate": 55,
            "description": "외상사건 관련 상황에 불편감을 느낌",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 중간 수준의 외상 스트레스를 자주 느끼고 있습니다. PTSD 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "ISI" : {
            "level": 87,
            "result": "심각함",
            "score" : 88,
            "riskRate": 77,
            "description": "심각한 불면증이 있는 것으로 보임",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 약간 심각한 수준의 불면증을 자주 느끼고 있습니다. 2주 이상 지속 시 전문가의 도움이 필요합니다. 수면 장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.\n",
        },
        "CSS" : {
            "result": "자살생각지속",
            "description": "자살 계획에 대한 생각을 하고 계신 것으로 보입니다.",
            "guidance": "추가 평가 및 전문가의 도움 즉시 권고",
            "advice": "전문도움필요",
            "details": "검사 결과는 자살 계획에 대한 생각을 하고 계신 것으로 보입니다. 우발적으로 자살 시도를 보일 가능성은 낮으나, 혹시라도 그러한 생각을 하고 계시다면 즉시 전문가의 도움을 받아보시길 권장드립니다.",
        },
    }
const data_4 =
    {
        "info": {
            "name": "test-5",
            "reservationNumber": 6110611061,
            "centerCode": 611,
            "examDate": "1989-02-17",
            "reportDate": "1989-02-19",
        },
        "KOSS": {
            "autonomy": {"distribution": "하위 25", "score": 13},
            "compensation": {"distribution": "상위 50", "score": 18},
            "culture": {"distribution": "상위 25", "score": 33},
            "jobInstability": {"distribution": "하위 25", "score": 46},
            "relationship": {"distribution": "상위 25", "score": 80},
            "requirements": {"distribution": "하위 50", "score": 100},
            "system": {"distribution": "상위 50", "score": 35},
            "total": {
                "distribution" : "상위 25",
                "score" : 55,
                "scoreMean" : 12.4,
                "level": 24,
                "result": "약간 심함",
                "byYear": 24,
                "details": "스트레스 측정 점수는 39.5점으로, 참고치 하위 25%에 해당합니다.",
            }
        },
        "PHQ9" : {
            "level": 87,
            "result": "심각함",
            "score" : 92,
            "riskRate": 88,
            "description": "우울감이 매우 자주, 심한 수준으로 느낌",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 심각한 수준의 우울감을 자주 느끼고 있습니다. 우울증 진단은 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.\n",
        },
        "GAD7" : {
            "level": 45,
            "result": "경미함",
            "score" : 33,
            "riskRate": 44,
            "description": "다소 경미한 수준의 걱정과 불안이 있음",
            "guidance": "직업, 사회적 영향이 있는지 주의 필요함",
            "advice": "주의필요",
            "byYear": 33,
            "details": "검사 결과는 경미함 수준의 불안감을 자주 느끼고 있습니다. 불안장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 주의가 필요합니다.",
        },
        "ADNM4" : {
            "level": 24,
            "result": "적응장애아님",
            "score" : 15,
            "riskRate": 18,
            "description": "일상생활 적응에 지장을 초래하지 않음",
            "guidance": "",
            "advice": "",
            "byYear": 22,
            "details": "검사 결과는 적응 스트레스가 없습니다.",
        },
        "PCPTSD5" : {
            "level": 87,
            "result": "심각함",
            "score" : 83,
            "riskRate": 88,
            "description": "외상사건 관련 상황에 심한 불편을 느낌",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 심각한 수준의 외상 스트레스를 자주 느끼고 있습니다. PTSD 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "ISI" : {
            "level": 45,
            "result": "경미함",
            "score" : 33,
            "riskRate": 35,
            "description": "경미한 불면증이 있는 것으로 보임",
            "guidance": "2주 이상 지속 시 전문가의 도움이 필요함",
            "advice": "주의필요",
            "byYear": 22,
            "details": "검사 결과는 경미한 수준의 불면증을 자주 느끼고 있습니다. 2주 이상 지속 시 전문가의 도움이 필요합니다. 수면 장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "CSS" : {
            "result": "자살행동고려",
            "description": "자살 시도를 할 가능성이 있으며, 자살 사고나 행동을 저지할 수 있는 보호 요인이 없는 것으로 보입니다.",
            "guidance": "추가 평가 및 전문가의 도움 즉시 권고",
            "advice": "전문도움필요",
            "details": "검사 결과는 자살 시도를 할 가능성이 있으며, 자살 사고나 행동을 저지할 수 있는 보호 요인이 없는 것으로 보입니다.",
        },
    }
const data_5 =
    {
        "info": {
            "name": "test-6",
            "reservationNumber": 6120612061,
            "centerCode": 612,
            "examDate": "1989-02-17",
            "reportDate": "1989-02-19",
        },
        "KOSS": {
            "autonomy": {"distribution": "하위 25", "score": 13},
            "compensation": {"distribution": "상위 50", "score": 18},
            "culture": {"distribution": "상위 25", "score": 33},
            "jobInstability": {"distribution": "하위 25", "score": 46},
            "relationship": {"distribution": "상위 25", "score": 80},
            "requirements": {"distribution": "하위 50", "score": 100},
            "system": {"distribution": "상위 50", "score": 35},
            "total": {
                "distribution" : "상위 25",
                "score" : 55,
                "scoreMean" : 12.4,
                "level": 24,
                "result": "약간 심함",
                "byYear": 24,
                "details": "스트레스 측정 점수는 39.5점으로, 참고치 하위 25%에 해당합니다.",
            }
        },
        "PHQ9" : {
            "level": 24,
            "result": "정상",
            "score" : 15,
            "riskRate": 18,
            "description": "우울 관련 증상이 거의 보이지 않음",
            "guidance": "",
            "advice": "",
            "byYear": 15,
            "details": "검사 결과는 경미한 수준의 우울감 위험이 있습니다.",
        },
        "GAD7" : {
            "level": 66,
            "result": "중간",
            "score" : 68,
            "riskRate": 54,
            "description": "주의가 필요한 과도한 걱정, 불안을 느낌",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 33,
            "details": "검사 결과는 중간 수준의 불안감을 자주 느끼고 있습니다. 불안장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "ADNM4" : {
            "level": 87,
            "result": "심각함",
            "score" : 69,
            "riskRate": 87,
            "description": "일상생활 적응에 어려움이 있을 수 있음",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 심각한 수준의 적응 스트레스를 자주 느끼고 있습니다. 적응장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "PCPTSD5" : {
            "level": 45,
            "result": "중간",
            "score" : 38,
            "riskRate": 55,
            "description": "외상사건 관련 상황에 불편감을 느낌",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 중간 수준의 외상 스트레스를 자주 느끼고 있습니다. PTSD 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "ISI" : {
            "level": 66,
            "result": "약간심함",
            "score" : 65,
            "riskRate": 66,
            "description": "중한 수준의 불면증이 있는 것으로 보임",
            "guidance": "추가 평가 또는 전문가의 도움이 필요함",
            "advice": "전문도움필요",
            "byYear": 22,
            "details": "검사 결과는 약간 심한 수준의 불면증을 자주 느끼고 있습니다. 2주 이상 지속 시 전문가의 도움이 필요합니다. 수면 장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "CSS" : {
            "result": "자살위험아님",
            "description": "위험한 수준의 자살 사고가 보이지 않음",
            "guidance": "",
            "advice": "",
            "details": "검사 결과는 자살사고 위험이 없습니다.",
        },
    }
const data_6 =
    {
        "info": {
            "name": "test-7",
            "reservationNumber": 7110711071,
            "centerCode": 711,
            "examDate": "1989-02-17",
            "reportDate": "1989-02-19",
        },
        "KOSS": {
            "autonomy": {"distribution": "하위 25", "score": 13},
            "compensation": {"distribution": "상위 50", "score": 18},
            "culture": {"distribution": "상위 25", "score": 33},
            "jobInstability": {"distribution": "하위 25", "score": 46},
            "relationship": {"distribution": "상위 25", "score": 80},
            "requirements": {"distribution": "하위 50", "score": 100},
            "system": {"distribution": "상위 50", "score": 35},
            "total": {
                "distribution" : "상위 25",
                "score" : 55,
                "scoreMean" : 12.4,
                "level": 24,
                "result": "약간 심함",
                "byYear": 24,
                "details": "스트레스 측정 점수는 39.5점으로, 참고치 하위 25%에 해당합니다.",
            }
        },
        "PHQ9" : {
            "level": 24,
            "result": "경미함",
            "score" : 25,
            "riskRate": 28,
            "description": "경미한 수준의 우울감이 있음",
            "guidance": "",
            "advice": "",
            "byYear": 22,
            "details": "검사 결과는 경미한 수준의 우울감 위험이 있습니다.",
        },
        "GAD7" : {
            "level": 24,
            "result": "불안아님",
            "score" : 15,
            "riskRate": 18,
            "description": "불안 관련 증상이 거의 보이지 않음",
            "guidance": "",
            "advice": "",
            "byYear": 44,
            "details": "검사 결과는 불안감이 없습니다.",
        },
        "ADNM4" : {
            "level": 24,
            "result": "적응장애아님",
            "score" : 15,
            "riskRate": 18,
            "description": "일상생활 적응에 지장을 초래하지 않음",
            "guidance": "",
            "advice": "",
            "byYear": 22,
            "details": "검사 결과는 적응 스트레스가 없습니다.",
        },
        "PCPTSD5" : {
            "level": 24,
            "result": "PTSD아님",
            "score" : 15,
            "riskRate": 18,
            "description": "일상생활을 저해하는 스트레스가 아님",
            "guidance": "",
            "advice": "",
            "byYear": 22,
            "details": "검사 결과는 외상 스트레스가 없습니다.",
        },
        "ISI" : {
            "level": 45,
            "result": "경미함",
            "score" : 33,
            "riskRate": 35,
            "description": "경미한 불면증이 있는 것으로 보임",
            "guidance": "2주 이상 지속 시 전문가의 도움이 필요함",
            "advice": "주의필요",
            "byYear": 22,
            "details": "검사 결과는 경미한 수준의 불면증을 자주 느끼고 있습니다. 2주 이상 지속 시 전문가의 도움이 필요합니다. 수면 장애 진단은 병력 및 여러 검사 결과와 전문의의 종합적인 판단에 의해 이루어지므로, 추가 평가 또는 전문가의 도움이 필요합니다.",
        },
        "CSS" : {
            "result": "CSS미검사자",
            "description": "정상입니다. 해당 검사를 수행할 필요가 없습니다.",
            "guidance": "",
            "advice": "",
            "details": "우울감 설문 결과에 따라 극단적 선택 가능성 검사를 진행하지 않았습니다.",
        },
    }
const data_7 =
    {
        "info": {
            "name": "null",
            "reservationNumber": 9110911091,
            "centerCode": 111,
            "examDate": "1989-02-17",
            "reportDate": "1989-02-19",
        },
        "KOSS": {
            "autonomy": {"distribution": "", "score": null},
            "compensation": {"distribution": "", "score": null},
            "culture": {"distribution": "", "score": null},
            "jobInstability": {"distribution": "", "score": null},
            "relationship": {"distribution": "", "score": null},
            "requirements": {"distribution": "", "score": null},
            "system": {"distribution": "", "score": null},
            "total": {
                "distribution" : "",
                "score" : null,
                "scoreMean" : null,
                "level": null,
                "result": "",
                "byYear": null,
                "details": "",
            }
        },
        "PHQ9" : {
            "level": null,
            "result": "",
            "score" : null,
            "riskRate": null,
            "description": "",
            "guidance": "",
            "advice": "",
            "byYear": null,
            "details": "",
        },
        "GAD7" : {
            "level": null,
            "result": "",
            "score" : null,
            "riskRate": null,
            "description": "",
            "guidance": "",
            "advice": "",
            "byYear": null,
            "details": "",
        },
        "ADNM4" : {
            "level": null,
            "result": "",
            "score" : null,
            "riskRate": null,
            "description": "",
            "guidance": "",
            "advice": "",
            "byYear": null,
            "details": "",
        },
        "PCPTSD5" : {
            "level": null,
            "result": "",
            "score" : null,
            "riskRate": null,
            "description": "",
            "guidance": "",
            "advice": "",
            "byYear": null,
            "details": "",
        },
        "ISI" : {
            "level": null,
            "result": "",
            "score" : null,
            "riskRate": null,
            "description": "",
            "guidance": "",
            "advice": "",
            "byYear": null,
            "details": "",
        },
        "CSS" : {
            "result": "",
            "description": "",
            "guidance": "",
            "advice": "",
            "details": "",
        },
    }
const data = [
    data_0, data_1, data_2, data_3, data_4, data_5, data_6, data_7
]


// Step 1: create connection
console.log("startingPoint-publisher")
//amqp.connect('amqp://tess_report:KHg4sZxTtjy3Aq4K@127.0.0.1:5672/kmi', (connectionError, connection) => {
amqp.connect('amqp://localhost', (connectionError: any, connection: any) => { // subscriber는 타입을 요구하지 않던데 음... 일단 any 처리
    console.log("tryConnection-publisher")
    if(connectionError) {
        console.log("connectionError-publisher")
        throw connectionError;
    }
    // Step 2: create channel
    connection.createChannel((channelError: any, channel: any) => { // subscriber는 타입을 요구하지 않던데 음... 일단 any 처리
        if(connectionError) {
            throw channelError;
        }
        // Step 3: assert queue
        const queueName = config.get('QUEUE_NAME')
        channel.assertQueue(queueName, {
            durable: false
        });
        // Step 4: send message to queue
        for (let i = 0; i < 8; i++) {
            const message = JSON.stringify(data[i])
            channel.sendToQueue(queueName, Buffer.from(message), {
                persistent: true
            });
            console.log(`[x] Sent data_${i} successfully.`)
        }
        // const message = JSON.stringify(data_2)
        // channel.sendToQueue(queueName, Buffer.from(message), {
        //     persistent: true
        // });
        // console.log(`[x] Sent data successfully.`)
    })
    setTimeout(() => {
        connection.close();
        process.exit(0)
    }, 1000)
})